# Welcome to Jekyll!

title: Roxo Jekyll
email: help@staticmania.com
description: Roxo | Creative Design Agency
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
# We're using formspree.io for form handling, paste your formspree url below
fabFormUrl: "https://fabform.io/f/Ecj6gBK"

# Build settings
gems:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 2
  permalink: '/blog/:num/'
  sort_field: 'date'
  sort_reverse: true

sass:
  sass_dir: _scss/
  style: compressed

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Portfolio
    url: /portfolio
  - title: Blog
    url: /blog
  - title: Get in touch
    url: /contact
    tag: special

# Call to action
call-to-action:
  enable                : true
  background_image      : "images/backgrounds/cta-background.jpg"
  title                 : "LETâ€™S WORK TOGETHER"
  primary_button        : "Submit Query"
  primary_button_url    : "/contact"
  secondary_button      : "Not Convinced"
  secondary_button_url  : "/portfolio"

# Footer
footer:
  contactInfo:
    title   : "Contact Info"
    address : "713 Elmwood St.<br>Prior Lake, MN 55372"
    phone   : "409-896-1444"
    email   : "info@roxo.co"
  sitemap:
    title: "Sitemap"
    link: 
      - name  : "About Company"
        url   : "/about"
      - name  : "Projects"
        url   : "/portfolio"
      - name  : "Blog"
        url   : "/blog"
      - name  : "Contact"
        url   : "/contact"
  social:
    title: "Social Media"
    link: 
      - name  : "Medium"
        url   : "#"
      - name  : "Behance"
        url   : "#"
      - name  : "Dribbble"
        url   : "#"
      - name  : "Instagram"
        url   : "#"
  service:
    title: "We help brands:"
    description: "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
